# Generated by Django 5.2.4 on 2025-08-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('wrestler_name', models.CharField(max_length=100)),
                ('wrestler_image', models.ImageField(blank=True, null=True, upload_to='wrestler_images/')),
                ('wrestler_description', models.TextField()),
            ],
        ),
    ]
